In [1]:
import cv2


In [2]:
photo = cv2.imread('img.png')

In [3]:
cv2.imshow('hi', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [4]:
photo.shape

(682, 817, 3)

In [5]:
photo[0][0]

array([ 40, 174, 104], dtype=uint8)

In [6]:
type(photo
    )

numpy.ndarray

In [7]:
photo

array([[[ 40, 174, 104],
        [ 40, 174, 104],
        [ 40, 174, 104],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[ 40, 174, 104],
        [ 40, 174, 104],
        [ 40, 174, 104],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[ 40, 174, 104],
        [ 40, 174, 104],
        [ 40, 174, 104],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[ 26,  19,  13],
        [ 26,  19,  13],
        [ 26,  19,  13],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[ 26,  19,  13],
        [ 26,  19,  13],
        [ 26,  19,  13],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[ 26,  19,  13],
        [ 26,  19,  13],
        [ 26,  19,  13],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]

In [8]:
photo[0][0]=[0,255,0]

In [9]:
cv2.imshow('hi', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [10]:
#photo[100]=[0,255,0]

In [11]:
cv2.imshow('hi', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [12]:
#crop the photo
cphoto = photo[200:500,150:500]


In [13]:
cv2.imshow('hi', photo)
cv2.waitKey()
cv2.destroyAllWindows()

In [14]:
import numpy

In [15]:
#essse apn ne khud ki black image bna li
#this will be a 2d array with all elements 0
cn = numpy.zeros((1000,1000))


In [16]:
type(cn)

numpy.ndarray

In [17]:
cv2.imshow('hiiii', cn)
cv2.waitKey()
cv2.destroyAllWindows()

In [18]:
cn

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [21]:
type(cn)

numpy.ndarray

In [22]:
cn.shape

(1000, 1000)

In [23]:
#3 elements honge or 3d array hai
cn1 = numpy.zeros((1000,1000,3))

In [26]:
cn

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [27]:
cn1

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [28]:
cn.shape

(1000, 1000)

In [29]:
cn1.shape

(1000, 1000, 3)

In [30]:
type(cn)

numpy.ndarray

In [31]:
type(cn1)

numpy.ndarray

In [32]:
#4 elements honge or 3d array hai
cn2 = numpy.zeros((1000,1000,4))


In [33]:
cn2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       ...,

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        ...,
        [0., 0., 0., 0.],
        [0., 0.

In [34]:
cn2.shape

(1000, 1000, 4)